backend:
  name: git-gateway
  branch: main

local_backend: true
  
media_folder: static/pets
public_folder: /public

collections:
  - name: "pets"
    label: "Aggiungi"
    folder: "pets/"
    create: true
    widget: "image"
    delete: false
    editor:
      preview: false
    fields:
      - { name: "foto", widget: "image" }
